#!/usr/bin/env bash
# reference: https://github.com/holman/dotfiles/blob/master/script/bootstrap

DOTFILES_ROOT=$(pwd)

info () {
	printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
	printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
	echo ''
	exit
}

link_file () {
	local src=$1 dst=$2

	local overwrite= backup= skip=
	local action=

	if [ -f $dst -o -d $dst -o -L $dst ]
	then

		local currentSrc="$(readlink $dst)"

		if [ "$currentSrc" == "$src" ]
		then
			skip=true;
		fi

		user "File already exists: $dst ($(basename "src")), what do you want to do?\n\
			[s]kip, [o]verwrite?"

		read -n 1 action

		case "$action" in
			s )
				skip=true;;
			o )
				overwrite=true;;
			* )
				;;
		esac
				
		if [ "$overwrite" == "true" ]
		then
			rm -rf "$dst"
			success "removed $dst"
		fi

		if [ "$skip" == "true" ]
		then
			success "skipped $src"
		fi
	fi

	if [ "$skip" != "true" ]
	then
		ln -s $1 $2
		success "linked $1 to $2"
	fi
}

install_dotfiles () {
	src="$DOTFILES_ROOT/.vimrc"
	dst="$HOME/$(basename "$src")"

	link_file "$src" "$dst"

	src="$DOTFILES_ROOT/.zshrc"
	dst="$HOME/$(basename "$src")"
	link_file "$src" "$dst"

	src="$DOTFILES_ROOT/.tmux.conf"
	dst="$HOME/$(basename "$src")"
	link_file "$src" "$dst"
}

install_dotfiles
